---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-sdk-harness-config
  labels:
    app: js-sdk-harness-worker
data:
  CONDUCTOR_SERVER_URL: "https://certification-az.orkesconductor.io/api"
  CONDUCTOR_AUTH_KEY: "bf170d61-2797-11f1-833e-4ae04d100a03"
